project_id = "yvmvttybgmgjgdekfupd"
[functions.chat-with-timmy]
enabled = true
verify_jwt = true
import_map = "./functions/chat-with-timmy/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chat-with-timmy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chat-with-timmy/*.html" ]
